name: Prepare
description: Prepares the repo for a typical CI job
runs:
  using: composite
  steps:
    - name: Checkouts from the branch
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: 20

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
